### ISSUE TITLE
Limit Which Section Can Be Dragged

### ISSUE THREAD

**Issue by s1rc** [nicolasgomollon/LPRTableView#2]
I have several sections in a table view and only want one of the sections to be draggable. Is this possible?

**Comment by nicolasgomollon** [comment]
It is possible to select which cells can be reordered by implementing the following standard `UITableViewDataSource` method:

``` swift
override func tableView(tableView: UITableView, canMoveRowAtIndexPath indexPath: NSIndexPath) -> Bool {
    // Change this logic to match your needs.
    return (indexPath.section == 0)
}
```

---

**NOTE:** Please update your copy of this repo, since I just noticed that the logic that enabled this was incorrect, and fixed it in 54f0c0c16ea608a3f5c795165a7440d104843421.
